# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieLens', '0003_auto_20160214_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='user',
            new_name='user_id',
        ),
    ]
